name: Test

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  test:
    strategy:
      matrix:
        python: ["3.9", "3.10"]
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l -e -o pipefail {0}

    services:
      irods:
        image: wsinpg/ub-18.04-irods-4.2.11
        ports:
          - 1247:1247
      
    env:
      WSI_CONDA_CHANNEL: "https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic"
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: |
            ~/conda/pkgs
            ~/conda/envs
          key: ${{ runner.os }}-miniconda

      - name: Setup conda
        run: |
          echo 'source $CONDA/etc/profile.d/conda.sh' >> "$HOME/.bash_profile"
          source $HOME/.bash_profile
          conda config --prepend pkgs_dirs "$HOME/conda/pkgs"
          conda config --prepend envs_dirs "$HOME/conda/envs"
          conda create -n conda-env
          conda activate conda-env
          conda config --add channels $WSI_CONDA_CHANNEL
          conda info
          
      - name: Install conda dependencies
        run: |
          conda activate conda-env
          conda install python=${{ matrix.python }}
          conda install baton irods-icommands

      - name: "Configure iRODS clients"
        run: |
          conda activate conda-env
          mkdir -p "$HOME/.irods"
          cat <<'EOF' > "$HOME/.irods/irods_environment.json"
          {
              "irods_host": "localhost",
              "irods_port": 1247,
              "irods_user_name": "irods",
              "irods_zone_name": "testZone",
              "irods_home": "/testZone/home/irods",
              "irods_default_resource": "replResc",
              "irods_default_hash_scheme": "MD5"
          }
          EOF
          echo "irods" | script -q -c "iinit" /dev/null
          ienv
          ilsresc
          ils
          baton-do --version

      - name: Setup Poetry
        run: |
          conda activate conda-env
          pip install poetry
          poetry install
          baton-do -h
      
      - name: Run tests
        run: |
          conda activate conda-env 
          poetry run pytest
